version: '3.9'

services:
  database:
    image: mysql:latest
    volumes:
      - application-db:/var/lib/mysql
    networks:
      - application
    ports:
      - "${DOCKER_PORT_DATABASE-}3306"
    environment:
      MYSQL_DATABASE: application
      MYSQL_USER: application
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - application
    ports:
      - "${DOCKER_PORT_PHPMYADMIN-}80"
    depends_on:
      - database
    environment:
      - PMA_USER=application
      - PMA_PASSWORD=password
      - PMA_HOSTS=database


  node:
    networks:
    - dockerhero

volumes:
  application-db:

networks:
  dockerhero:
    external:
      name: dockerhero_dockerhero
